### ISSUE TITLE
EWBF miner dies and not restarts

### ISSUE THREAD

**Issue by egorfedorov29** [egorfedorov29/hellomoto22#1]
previous is ZEC nvidia

INFO 00:48:47: GPU5 Accepted share 47ms [A:12, R:0]
INFO 00:48:52: GPU3 Accepted share 50ms [A:9, R:0]
2017-12-15 00:49:00,004|statistic_manager|INFO: Send stat...
#  profit: 19.59 USD, worker: digger12, mining: BTG(nvidia)
2017-12-15 00:49:01,234|task_manager|INFO: Get task 'switch_miner'
2017-12-15 00:49:01,234|client    |INFO: New mining config 'BTG(nvidia)'
2017-12-15 00:49:03,288|miner_monitor|ERROR: Exception when switch miner <class 'PermissionError'>
2017-12-15 00:49:03,288|miner_monitor|WARNING: Miner not run. Going to restart after 8 seconds
2017-12-15 00:49:11,302|miner_monitor|ERROR: Exception while restart died miner: <class 'PermissionError'>
2017-12-15 00:49:12,312|miner_monitor|WARNING: Miner not run. Going to restart after 8 seconds
2017-12-15 00:49:20,328|miner_monitor|ERROR: Exception while restart died miner: <class 'PermissionError'>
2017-12-15 00:49:21,332|miner_monitor|WARNING: Miner not run. Going to restart after 8 seconds
2017-12-15 00:49:29,347|miner_monitor|ERROR: Exception while restart died miner: <class 'PermissionError'>
2017-12-15 00:49:30,194|statistic_manager|INFO: Send stat...
2017-12-15 00:49:30,350|miner_monitor|WARNING: Miner not run. Going to restart after 8 seconds
#  profit: 0.0 USD, worker: digger12, mining: BTG(nvidia)

**Comment by egorfedorov29** [comment]
appears in digger12

**Comment by egorfedorov29** [comment]
workaround solution is to exit from app and allow starter to reload.
At least when i kill python from task manager i got normal startup

**Comment by bestchanges** [comment]
Проблема более чем актуальна

Traceback (most recent call last):
  File "bestminer-client.py", line 876, in run
    self.miner_manager.run_miner()
  File "bestminer-client.py", line 649, in run_miner
    os.unlink(log_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'miners\\ewbf_win\\miner.log'

Exception while restart died miner: [WinError 32] The process cannot access the file because it is being used by another process: 'miners\\ewbf_win\\miner.log'
<Request 'http://test.bestminer.io/client/stat?os=Windows&rig_id=eca252bb-b296-5ef0-986a-b1458fff626e&email=harrifik%40yandex.ru&secret=h0b3i5' [PUT]>
b'{"miner_stdout": "", "pu_temperatire": ["67", "59", "50", "54", "51", "54"], "config": {"worker": "miner_three", "miner_config": {"read_output": false, "config_name": "ZEC(nvidia)", "miner_command_line": "--server eu1-zcash.flypool.org --port 3333 --user t1LGPDd4qFhh14vrcAqpZjFMeDhwPF9exgb.miner_three --log 2 --pass x --eexit 3 --fee 0.5", "miner_family": "ewbf", "miner": "EWBF", "miner_directory": "ewbf_win", "miner_version": "0.3.4b", "env": {"GPU_MAX_HEAP_SIZE": "100", "GPU_SINGLE_ALLOC_PERCENT": "100", "GPU_MAX_ALLOC_PERCENT": "100", "GPU_USE_SYNC_OBJECTS": "1"}, "miner_exe": "miner.exe", "miner_code": "ewbf"}, "server": "test.bestminer.io", "task_manager": {"request_interval_sec": 15}, "statistic_manager": {"request_interval_sec": 30}, "rig_id": "eca252bb-b296-5ef0-986a-b1458fff626e", "client_version": "0.31", "email": "harrifik@yandex.ru", "logger": {"port": 9020, "server": "test.bestminer.io"}}, "client_version": "0.31", "processing_units": [], "miner": {"is_run": true, "miner_config": {"read_output": false, "config_name": "ZEC(nvidia)", "miner_command_line": "--server eu1-zcash.flypool.org --port 3333 --user t1LGPDd4qFhh14vrcAqpZjFMeDhwPF9exgb.miner_three --log 2 --pass x --eexit 3 --fee 0.5", "miner_family": "ewbf", "miner": "EWBF", "miner_directory": "ewbf_win", "miner_version": "0.3.4b", "env": {"GPU_MAX_HEAP_SIZE": "100", "GPU_SINGLE_ALLOC_PERCENT": "100", "GPU_MAX_ALLOC_PERCENT": "100", "GPU_USE_SYNC_OBJECTS": "1"}, "miner_exe": "miner.exe", "miner_code": "ewbf"}}, "pu_fanspeed": [], "hashrate": {"current": {"Equihash": 2044.0}, "target": {}}, "pu_types": [], "reboot_timestamp": 1524862852}'
<Request 'http://test.bestminer.io/client/stat?os=Windows&email=andrey.skripchenko%40gmail.com&rig_id=d8e94b33-d40a-5c32-b34b-d226646d9ba4&secret=cdszyc' [PUT]>
b'{"pu_fanspeed": [], "reboot_timestamp": 1523578751, "miner": {"miner_config": {"miner": "EWBF", "read_output": false, "miner_command_line": "--server us-east.equihash-hub.miningpoolhub.com --port 20594 --user a6848418.%W1% --log 2 --pass x --eexit 3 --fee 0.5", "env": {}, "config_name": "ZEN(nvidia)", "miner_version": "0.3.4b", "miner_directory": "ewbf_win", "miner_code": "ewbf", "miner_exe": "miner.exe", "miner_family": "ewbf"}, "is_run": true}, "pu_types": [], "miner_stdout": "", "pu_temperatire": [], "processing_units": [], "client_version": "0.31", "hashrate": {"current": {}, "target": {}}, "config": {"task_manager": {"request_interval_sec": 15}, "miner_config": {"miner": "EWBF", "read_output": false, "miner_command_line": "--server us-east.equihash-hub.miningpoolhub.com --port 20594 --user a6848418.%W1% --log 2 --pass x --eexit 3 --fee 0.5", "env": {}, "config_name": "ZEN(nvidia)", "miner_version": "0.3.4b", "miner_directory": "ewbf_win", "miner_code": "ewbf", "miner_exe": "miner.exe", "miner_family": "ewbf"}, "rig_id": "d8e94b33-d40a-5c32-b34b-d226646d9ba4", "logger": {"port": 9020, "server": "test.bestminer.io"}, "worker": "W4", "client_version": "0.31", "email": "andrey.skripchenko@gmail.com", "server": "test.bestminer.io", "statistic_manager": {"request_interval_sec": 30}}}'
Miner connot be restarted. Exit after 13 attempts
